[package]
name = "speech-over"
version = "0.1.0"
edition = "2021"

[dependencies]
zbus = "2.2.0"

[dependencies.async-std]
version = "1.11.0"
features = ["attributes"]

[dependencies.at-spi]
version = "0.1.0"
path = "at-spi"

[workspace]
members = [
  "at-spi"
]
